name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Code
        run: echo "Cloning the Code"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build using Docker
        run: echo "Building using Docker"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running Tests"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying Application"
